### ISSUE TITLE
TypeError: '<' not supported between instances of 'NoneType' and 'int' (for unconfirmed txs)

### ISSUE THREAD

**Issue by k9ert** [wombat6/specterext-stacktrack#12]
This is happening for unconfirmed txs:
```
[2023-01-24 11:44:15,601] ERROR in controller: Uncaught exception: '<' not supported between instances of 'NoneType' and 'int'
[2023-01-24 11:44:15,606] ERROR in controller: Traceback (most recent call last):
  File "/home/kim/src/specter-desktop/.env/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kim/src/specter-desktop/.env/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kim/src/specter-desktop/.env/lib/python3.10/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/kim/src/specter-desktop/.env/lib/python3.10/site-packages/cryptoadvance/specterext/stacktrack/controller.py", line 79, in wallets_overview
    txs: list = _extract_txs(wallets)
  File "/home/kim/src/specter-desktop/.env/lib/python3.10/site-packages/cryptoadvance/specterext/stacktrack/controller.py", line 124, in _extract_txs
    return sorted(txs, key=lambda d: d["blockheight"], reverse=True)
TypeError: '<' not supported between instances of 'NoneType' and 'int'

[2023-01-24 11:44:15,607] INFO in _internal: 127.0.0.1 - - [24/Jan/2023 11:44:15] "GET /svc/stacktrack/wallets_overview HTTP/1.1" 500 -
```

**Comment by k9ert** [comment]
Reasonable complaints for unconfirmed Txs:
```
    # Reverse sort, like wallets do
    return sorted(txs, key=lambda d: d["blockheight"], reverse=True)
```

**Comment by moneymanolis** [comment]
My suggestion would be to exclude unconfirmed tx [here](https://github.com/cryptoadvance/specterext-stacktrack/blob/0bfb2abcf52fb1be3a7d3117f2b46adb44230906/src/cryptoadvance/specterext/stacktrack/controller.py#L127). Unconfirmed tx amounts shouldn't be considered in the chart yet anyways. @wombat6 what do you think? I love the feature in general. Great work!

**Comment by moneymanolis** [comment]
@noubre might be interesting to you.
